choco install git
choco install tortoisegit
choco install tortoisesvn
choco install googlechrome
choco install flashplayerplugin
choco install flashplayeractivex
choco install notepadplusplus
choco install 7zip
choco install skype
choco install sysinternals
choco install dotnet4.5.2
choco install battle.net
choco install steam
choco install keepass
choco install sublimetext3
choco install deluge
choco install teamviewer
choco install jdownloader -pre
choco install mumble
choco install discord
choco install teamspeak
choco install hexchat
choco install autohotkey
choco install autoit
choco install cheatengine
choco install malwarebytes
choco install sharex
choco install calibre
choco install foobar2000
choco install speccy
choco install cpu-z
choco install yumi
choco install eclipse
choco install filebot
choco install plexmediaserver